version: '3.8'
name: lab

services:
  api:
    build:
      context: ./monolith
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/libros
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8002:80"

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount init.sql into the container
    command: [ '--init-file', '/docker-entrypoint-initdb.d/init.sql' ] # Execute init.sql on container startup

volumes:
  db_data:

    # Deploy a database, a frontend, an API, and a microservice. Github Actions.
    # 0. BD, Front / Backend / Microservicio +OK
    # 1. Communicate API with DB
    # 2. Communicate Frontend with Backend
    # 4. Deploy with terraform ECR.
